### PR TITLE
Simple enzyme unit testing

### PR DESCRIPTION
**Pull request by shilman**
@tmeasday Here is a version of enzyme testing that's implemented directly using meteor testing.

How to run:
```
meteor npm install
meteor npm run test-watch
```

Note: I had a hell of a time with NPM versioning and still didn't really figure it out.
 - Enzyme requires React 15.0.0, so I downgraded React.
 - When I run test-watch on my machine, it restarts three times with this error:
```
Unable to resolve some modules:

  "react/addons" in /Users/shilman/projects/todos/node_modules/enzyme/build/react-compat.js (web.browser)
  "react/lib/ReactContext" in /Users/shilman/projects/todos/node_modules/enzyme/build/react-compat.js (web.browser)
  "react/lib/ExecutionEnvironment" in /Users/shilman/projects/todos/node_modules/enzyme/build/react-compat.js (web.browser)
```
 - It mysteriously succeeds on the fourth fourth try, and the tests run properly as expected.

### CODE REVIEW

**Comment by tmeasday** [comment]
Hi @shilman,

Looks great. PS what problems did you have with npm? I reverted some of your changes to `package.json` (like the React version) and was able to successfully install and run `npm shrinkwrap --dev`

**Comment by shilman** [comment]
@tmeasday I reverted the react version and updated the PR. Sadly it was a long and circuitous path to something pretty simple. The kicker for me was that weird test-watch restarting issue I mentioned above---I thought it was a package versioning problem, and tried all kinds of version gymnastics before I realized it was a non-issue.

Next, I'll add some interaction tests and a sprinkling of component tests to wrap this up.

**Comment by shilman** [comment]
@tmeasday Interaction tests added and working. Ideally I'd be able to stub this code:

```js
import {
  setCheckedStatus,
  updateText,
  remove,
} from '../../api/todos/methods.js';
```

Instead of the awkward pattern I'm using right now (easily seen in my hacky mods to `TodoItem.jsx`). Any suggestions for how to best do this?

**Comment by tmeasday** [comment]
>  it was a long and circuitous path to something pretty simple

Better than a long and circuitous path to something complex if you ask me.

> Interaction tests added and working

They look great!

> Instead of the awkward pattern...

Can you do this:

```
import * as methods from '../../api/todos/methods.js';

sinon.stub(methods, 'setCheckedStatus', ...);
```

(I've not tried the above but it seems like it should work. Let me know if you can't make it work and I'll give it a try).

**Comment by shilman** [comment]
@tmeasday Ok, I think this is a nice pattern now. I'll write tests for a few other components to finish things off.

**Comment by shilman** [comment]
@tmeasday Filled in a few `ListHeader` tests and updated the pattern a little bit.

There's one FIXME in the code which I could use feedback on, and a small modification to the original source to make up for deficiencies in enzyme selectors as far as I could tell. Otherwise I think it's a good start.

Let me know if there are improvements you'd like to see, or other UI components that you think could particularly benefit from testing!

**Comment by tmeasday** [comment]
Great stuff @shilman. 

1. I think the source change is totally fine.

2. I'm not sure I understand the FIXME properly -- is this an enzyme problem we need to work around? I don't think it's a big deal.

3. One improvement: maybe separating the setup, test and verification steps of each test via whitespace (i.e. some blank lines) might make the tests easier to understand.

**Comment by shilman** [comment]
@tmeasday Thanks, I updated spacing. Not a huge improvement IMO but whatevs. 😄 

The FIXME is not a problem so I removed it. But my point was that (1) ideally the following snippets should be equivalent, with the former simulating a user action, and the latter just setting data directly, and (2) the former is preferable because it tests a little more: 

```js
        header.find('.todo-new').find('input[type="text"]').simulate('change', { target: { value: 'new todo' } });
        header.find('.todo-new').simulate('submit');
```

```js
        header.instance().refs.newTodoInput.value = 'new todo';
        header.find('.todo-new').simulate('submit');
```

However, the first code does not work as I'd hoped. If you agree with the former being preferable and have any ideas about how to fix it, that would be great.

**Comment by tmeasday** [comment]
I suspect the reason the snippet doesn't work is that the `simulate` method is just for triggering React event handlers, not specifically for performing DOM compatible changes. If the `newTodoInput` was a "bound" input (i.e had `value={this.state.X} onChange={e => this.state.X = e.value`) that could would probably..

**Pull request merged**
