### PR TITLE
Giving the todos app some love (meteor version / deps / lint updates)

### PR DESCRIPTION
**Pull request by hwillson**
Hi guys - here's a quick PR to bring the Blaze version of the todos app up to date in terms of Meteor version, packages, deps, etc. Here's a more detailed breakdown:

- Updated to Meteor 1.4.1.1
- Updated all packages to their latest versions (excluding indirect dependencies)
- Updated all npm dependencies/devDependencies to their latest versions
- Fixed all new linting errors caused by updates to the airbnb configs; for the most part all updates followed the default recommendations of the airbnb config, with a few exceptions. When the todos app veers significantly from the default airbnb rules, instead of updating the full codebase I've adjusted the rules to either allow exceptions or turn them off. The main rules affected are:
  `import/prefer-default-export` - since default exports aren't really used in the todos app I've shut this rule off. 
  `object-shorthand` - I've set avoidQuotes to false to disable the error when using object shorthand syntax with string literals (which the todos app does in a few places).

I'll update the `react` branch as well. Let me know if you have any questions or want anything changed. Thanks!

### CODE REVIEW

**Comment by tmeasday** [comment]
Appreciate this @hwillson! It looks like the `package.json` is NQR though -- the eslint plugins are at the wrong versions maybe? (see test failure)

**Comment by hwillson** [comment]
Hi @tmeasday - yes, I'm looking at it now. Updates coming shortly. Thanks!

**Comment by hwillson** [comment]
Sorry about that @tmeasday - the versions were okay but I didn't notice the shrinkwrap that was in place. I've updated the shrinkwrap so things should now build properly. That being said, CircleCI is taking quite a while with the build - it's still queued (has been for about 30 minutes now). I'll keep an eye on it but something seems a little off.

**Comment by tmeasday** [comment]
No worries. I think circle is just backed up behind some meteor commits right now, nbd.

**Comment by hwillson** [comment]
Great - looks better now @tmeasday; thanks again.

BTW - I know you guys are swamped with Apollo these days, so if you're ever looking for a hand with managing this repo, I'd be glad to join in and help clear out PR's, keep things up to date, etc.

**Comment by tmeasday** [comment]
That'd be great! I'll add you as a maintainer

**Comment by hwillson** [comment]
Awesome - thanks!

**Pull request merged**
