### PR TITLE
Created validation error package based entirely from SS

### PR DESCRIPTION
**Pull request by tmeasday**

### CODE REVIEW

**Comment by tmeasday** [comment]
Works for you?

**Comment by stubailo** [comment]
Yeah looks great! It would be good to have a catalog somewhere of exactly what possible properties there are for that details field.

**Comment by tmeasday** [comment]
For now, I just copied SS, which has a single string `value` and then you provide "translations" which can optionally include `[value]` to interpolate it. However I am anticipating that people may want to include more than one dimension on an error (e.g. `{name: 'title', type: 'outOfRange', details: {value: 27, max: 3}`).

Do you think I should just go straight to that version?

**Comment by stubailo** [comment]
Yeah, I think details as an object would be a good idea. Perhaps `value` could be a convention as one of the properties of `details`. `name` is the name of the field, `type` is the name of the validator, and so I guess `details` would be everything else.

**Pull request merged**
