### PR TITLE
Instead of storing `todo.userId`, use publish composite to control th…

### PR DESCRIPTION
**Pull request by tmeasday**
…e publication.

### CODE REVIEW

**Comment by stubailo** [comment]
We need to update the method tests, since they check that the denormalization worked.

**Comment by tmeasday** [comment]
Yup, was going to do that, just wanted to check with you that it still made sense given this comment: https://github.com/meteor/todos/issues/48#issuecomment-158839826

**Comment by stubailo** [comment]
Oh that's interesting. That actually might be a good reason to keep the denorm... we could probably get it to 0 lookups.

**Comment by tmeasday** [comment]
I'm not sure what the priority here is. There are a few competing things:

1. Achieving best performance (seems misguided? but we do it in other places)
2. Demonstrating the most patterns for the guide
3. Being a clear and simple example app

Actually all three things compete with each other. I'm not sure what's best. Let's discuss tomorrow.

**Comment by stubailo** [comment]
I think we should go with "4: Write what we would do in a real app" - and I think I'd probably do the publish-composite thing until it became a real performance issue. So I think we should take the PR.

**Comment by tmeasday** [comment]
This is ready to merge, I'll let you hit the button and double check @stubailo

**Comment by stubailo** [comment]
Looks great - I rebased on master

**Pull request merged**
