### PR TITLE
Experimental use of `dynamic-import` in the coming Meteor 1.5 release…

### PR DESCRIPTION
**Pull request by szchenghuang**
… based upon route change.

The beta release in use is the latest Meteor 1.5-beta.10 as of today.

### CODE REVIEW

**Comment by hwillson** [comment]
Hi @szchenghuang - thanks for submitting this! Since 1.5 is in beta however, we'll have to hold off on merging this for now (since `todos` is the reference application of the [Guide](https://guide.meteor.com), which documents officially released functionality only). We can keep this open though, and we'll definitely re-visit when 1.5 is released. Thanks again!

**Comment by szchenghuang** [comment]
No probles. Feel free to merge at any appropriate time.

**Comment by abernix** [comment]
Would you consider rebasing this with the official Meteor 1.5 release now that it's out, @szchenghuang?

**Comment by szchenghuang** [comment]
Will do.

**Comment by szchenghuang** [comment]
I have rebased this ticket and updated it to the major release 1.5.

**Comment by hwillson** [comment]
@szchenghuang Thanks again for submitting this PR. As part of a separate round of refactoring work however, we've updated `todos` to use `react-router` 4. This means the routing structure has been changed around a bit, and your code changes are no longer directly applicable. If you're interested in submitting new `dynamic-import` changes that line up with the `react-router` 4 changes, that would be awesome! If so, please do so in a new PR. Thanks very much!

**Pull request closed without merging**
