### PR TITLE
Update README.md to reflect 1.3-modules-beta

### PR DESCRIPTION
**Pull request by cheapRoc**
This should properly satisfy two other recent issues users had with the modules beta.

### CODE REVIEW

**Comment by stubailo** [comment]
@cheapRoc this should happen automatically - the `.meteor/release` file in the app should tell the Meteor tool to run the right version. Does that not work for you?

**Comment by cheapRoc** [comment]
I understand and it is working for me.

The update instructions aren't required but I still believe it's worth mentioning the beta target in the README in some fashion other than, "This app uses the module functionality from the upcoming Meteor 1.3". Just for the sake of being clear. 

You know how it is with betas and version numbers. :)

**Comment by stubailo** [comment]
Looking forward to your PR updating the version with each new beta release :)

**Comment by cheapRoc** [comment]
Well I do need more responsibility in my life so GAME ON!

**Pull request merged**
