### PR TITLE
Control reactivity using fields an a wrapper function.

### PR DESCRIPTION
**Pull request by tmeasday**
This way `listShow` is a "reusable" component. Yay.

Thoughts @stubailo? How to refactor to avoid the f -> f -> f?

### CODE REVIEW

**Comment by tmeasday** [comment]
1. Use array of IDs, not `{_id}`s
2. Try `{{> listShow (listArgs listId)}}`

**Comment by tmeasday** [comment]
Ok, done. Please review @stubailo

**Comment by tmeasday** [comment]
We should merge this and update the code examples

**Comment by stubailo** [comment]
Looks awesome!

**Pull request merged**
