### PR TITLE
Extract publication collector to separate package

### PR DESCRIPTION
**Pull request by johanbrook**
This PR extracts the tester helper package `publication-collector` into a separate package at `johanbrook:publication-collector`, from discussion in https://github.com/meteor/todos/issues/119.

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks @johanbrook!

**Comment by lorensr** [comment]
When this is tested/merged, also check out https://github.com/meteor/guide/pull/460

**Comment by lorensr** [comment]
Oops, my page hadn't updated :) On it

**Comment by tmeasday** [comment]
I tested it and it does indeed work :)

**Comment by johanbrook** [comment]
⚡ ⚡ ⚡

**Pull request merged**
