### PR TITLE
Move head.html to /client/

### PR DESCRIPTION
**Pull request by kachkaev**
This file was no longer picked by meteor after moving it to /includes/ui/

### CODE REVIEW

**Comment by stubailo** [comment]
shouldnt we just import it then?

**Comment by stubailo** [comment]
Actually I'm curious if it will still work. We should check

**Comment by pronevich** [comment]
This file still in imports and not imported on client.

**Comment by ciro207** [comment]
it works for me, but if we want to use multiple head depending on page?

**Comment by tmeasday** [comment]
@stubailo it seems like you can't import it (I guess because it doesn't compile to a JS template).

**Comment by smeijer** [comment]
How does this work with a disabled eagerloading with `package.json` `mainModule`?

```json
"meteor": {
  "mainModule": {
    "client": "client/main.js",
    "server": "server/main.js"
  }
},
```

`client/head.html` doesn't get eager loaded here, but `import './head.html'` in `client/main.js` doesn't work either.

**Pull request merged**
