### PR TITLE
Useraccounts configuration fix

### LINKED ISSUE #148: Reset password workflow will not work
I was just testing the password reset functionality in an app I'm building based loosely on this one.  Long story short, according to the documentation of the useraccounts package (https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api), configuration should be done on both the client and server.

Specifically, I was seeing this issue (https://github.com/meteor-useraccounts/core/issues/277#issuecomment-73570792), and a comment at the end of the thread pointed me in the right direction.

I'll create a pull request with my particular solution shortly.

Note: I'm not sure how many people this would affect anyway, but it was a little frustrating when I expected the demo app to have all the basics working.

### PR DESCRIPTION
**Pull request by jdivy**
Create startup configuration for both client and server; Fix useraccounts

Fixes #148, in particular the *reset password* functionality, but perhaps other things as well.

### CODE REVIEW

**Comment by LiamBigelow** [comment]
Would also be wise to include the verifyEmail route

```
AccountsTemplates.configureRoute('verifyEmail', {
  name: 'verify-email',
  path: '/verify-email',
});
```

Otherwise the email verification options hit a page not found.

**Comment by rub1e** [comment]
This looks good - I was about to do a similar PR before I saw this - discussion on meteor forum [here](https://forums.meteor.com/t/meteor-guide-users-and-accounts/19664/16).

@jdivy for my own edification, is there a reason you moved the routes to the configuration file, or just personal preference? (I can see it both ways, just curious)

**Comment by stubailo** [comment]
Did we ever do the verifyEmail thing? Also, does this app even require emails to be verified?

**Comment by jdivy** [comment]
@rub1e I just decided to lump all of the useraccounts config into one file, including routes as well of course,  since (in my head at least) it requires unique treatment.  I guess it made more sense to put all the useraccounts stuff in one place at the time.

@stubailo I don't think the app ever actually exercises the verify email workflow, for what it's worth

Also, I noticed that @tmeasday is working on transitioning the entire app to Apollo ( 👍 ) in #167 so this PR is perhaps completely moot.  Would be nice to transfer the proper configuration into it though, so something to keep in mind!

**Comment by stubailo** [comment]
We're doing the apollo thing mostly as an experiment. We're probably going to focus on a different example app to start with, but this can be a good training ground for migration strategies.

**Pull request merged**
