### PR TITLE
remove watch flag from list ui acceptance test

### PR DESCRIPTION
**Pull request by DominikGuzei**
Any test case that has the @watch flag will not be run by chimp in CI mode (so the single test is actually not executed atm). This flag should only be used during development.

This also solves the issue @noahsw mentioned in https://github.com/meteor/todos/pull/164

### CODE REVIEW

**Comment by noahsw** [comment]
Good catch! Why aren't the unit and full-app tests run anymore?

**Comment by DominikGuzei** [comment]
@noahsw because they failed horribly (errors all around) and i had no time to fix them too – but they should definitely be included again.

**Comment by noahsw** [comment]
@DominikGuzei - the unit and full-app tests run just fine for me on master.

```
─± meteor npm test

> @ pretest /Users/noah/Projects/docs/meteor-todos
> npm run lint --silent


> @ test /Users/noah/Projects/docs/meteor-todos
> meteor test --once --driver-package dispatch:mocha-phantomjs

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.4.0.1 is available. Update this project with 'meteor update'.
I20160804-18:27:30.070(-7)?
I20160804-18:27:30.190(-7)? --------------------------------
I20160804-18:27:30.191(-7)? ----- RUNNING SERVER TESTS -----
I20160804-18:27:30.192(-7)? --------------------------------
I20160804-18:27:30.192(-7)?
I20160804-18:27:30.192(-7)?
I20160804-18:27:30.192(-7)?
I20160804-18:27:30.730(-7)?   lists
I20160804-18:27:30.740(-7)?     mutators
I20160804-18:27:30.756(-7)?
I20160804-18:27:30.758(-7)?       ✓ builds correctly from factory
I20160804-18:27:30.773(-7)?     publications
=> Started your app.

=> App running at: http://localhost:3000/
I20160804-18:27:30.934(-7)?       lists.public
I20160804-18:27:30.956(-7)?
I20160804-18:27:30.956(-7)?         ✓ sends all public lists
I20160804-18:27:30.957(-7)?       lists.private
I20160804-18:27:30.965(-7)?
I20160804-18:27:30.967(-7)?         ✓ sends all owned lists
I20160804-18:27:30.967(-7)?     methods
I20160804-18:27:30.967(-7)?       makePrivate / makePublic
I20160804-18:27:31.042(-7)?
I20160804-18:27:31.042(-7)?         ✓ makes a list private and updates the todos
I20160804-18:27:31.072(-7)?
I20160804-18:27:31.073(-7)?         ✓ only works if you are logged in
I20160804-18:27:31.095(-7)?
I20160804-18:27:31.096(-7)?         ✓ only works if it's not the last public list
I20160804-18:27:31.142(-7)?
I20160804-18:27:31.143(-7)?         ✓ only makes the list public if you made it private
I20160804-18:27:31.144(-7)?       updateName
I20160804-18:27:31.174(-7)?
I20160804-18:27:31.175(-7)?         ✓ changes the name, but not if you don't have permission
I20160804-18:27:31.175(-7)?       remove
I20160804-18:27:31.197(-7)?
I20160804-18:27:31.197(-7)?         ✓ does not delete the last public list
I20160804-18:27:31.226(-7)?
I20160804-18:27:31.227(-7)?         ✓ does not delete a private list you don't own
I20160804-18:27:31.228(-7)?       rate limiting
I20160804-18:27:31.647(-7)?
I20160804-18:27:31.648(-7)?         ✓ does not allow more than 5 operations rapidly (392ms)
I20160804-18:27:31.665(-7)?
I20160804-18:27:31.665(-7)?   todos
I20160804-18:27:31.702(-7)?
I20160804-18:27:31.703(-7)?     ✓ leaves createdAt on update
I20160804-18:27:31.708(-7)?     mutators
I20160804-18:27:31.748(-7)?
I20160804-18:27:31.748(-7)?       ✓ builds correctly from factory
I20160804-18:27:31.753(-7)?     publications
I20160804-18:27:31.877(-7)?       todos.inList
I20160804-18:27:31.891(-7)?
I20160804-18:27:31.893(-7)?         ✓ sends all todos for a public list
I20160804-18:27:31.897(-7)?
I20160804-18:27:31.898(-7)?         ✓ sends all todos for a public list when logged in
I20160804-18:27:31.907(-7)?
I20160804-18:27:31.908(-7)?         ✓ sends all todos for a private list when logged in as owner
I20160804-18:27:31.910(-7)?
I20160804-18:27:31.910(-7)?         ✓ sends no todos for a private list when not logged in
I20160804-18:27:31.914(-7)?
I20160804-18:27:31.925(-7)?         ✓ sends no todos for a private list when logged in as another user
I20160804-18:27:31.926(-7)?
I20160804-18:27:31.926(-7)?
I20160804-18:27:31.926(-7)?   18 passing (2s)
I20160804-18:27:31.927(-7)?
I20160804-18:27:31.927(-7)?
I20160804-18:27:31.927(-7)? --------------------------------
I20160804-18:27:31.928(-7)? ----- RUNNING CLIENT TESTS -----
I20160804-18:27:31.928(-7)? --------------------------------
I20160804-18:27:31.929(-7)?
I20160804-18:27:32.461(-7)?
I20160804-18:27:32.462(-7)?
I20160804-18:27:32.479(-7)?   Lists_show

I20160804-18:27:32.527(-7)?     ✓ renders correctly with simple data (44ms)
I20160804-18:27:32.528(-7)?
I20160804-18:27:32.529(-7)?   Todos_item
I20160804-18:27:32.532(-7)?     ✓ renders correctly with simple data
I20160804-18:27:32.535(-7)?     ✓ renders correctly when checked
I20160804-18:27:32.537(-7)?     ✓ renders correctly when editing
I20160804-18:27:32.538(-7)?
I20160804-18:27:32.538(-7)?   Lists_show_page
I20160804-18:27:32.564(-7)?     ✓ renders correctly with simple data
I20160804-18:27:32.565(-7)?
I20160804-18:27:32.565(-7)?
I20160804-18:27:32.566(-7)?   5 passing (104ms)
I20160804-18:27:32.566(-7)?
I20160804-18:27:32.569(-7)? stdout:

I20160804-18:27:32.569(-7)? stdout:

I20160804-18:27:32.570(-7)? stdout:

I20160804-18:27:32.570(-7)? stdout:

I20160804-18:27:32.573(-7)? stdout:
I20160804-18:27:32.604(-7)? MochaRunner.runServerTests: Starting server side tests with run id 3qituo3GFn59gDk9T
I20160804-18:27:32.611(-7)? ClientServerReporter.constructor: Missing reporter to run tests. Use MochaRunner.setReporter(reporter) to set one.
W20160804-18:27:32.640(-7)? (STDERR) MochaRunner.runServerTests: failures: 2   <==== NOT SURE WHY THIS SAYS 2 FAILURES WHEN BELOW SAYS 0
I20160804-18:27:36.977(-7)? All client and server tests finished!
I20160804-18:27:36.978(-7)?
I20160804-18:27:36.979(-7)? --------------------------------
I20160804-18:27:36.979(-7)? SERVER FAILURES: 0
I20160804-18:27:36.979(-7)? CLIENT FAILURES: 0
I20160804-18:27:36.980(-7)? --------------------------------
╭─noah at MacBook-Pro in ~/Projects/docs/meteor-todos  (master ✘)
╰─± meteor npm run test-app

> @ test-app /Users/noah/Projects/docs/meteor-todos
> meteor test --full-app --once --driver-package dispatch:mocha-phantomjs

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.4.0.1 is available. Update this project with 'meteor update'.
I20160804-18:28:39.690(-7)?
I20160804-18:28:39.795(-7)? --------------------------------
I20160804-18:28:39.797(-7)? ----- RUNNING SERVER TESTS -----
I20160804-18:28:39.797(-7)? --------------------------------
I20160804-18:28:39.797(-7)?
I20160804-18:28:39.797(-7)?
I20160804-18:28:39.798(-7)?
I20160804-18:28:39.798(-7)?   0 passing (0ms)
I20160804-18:28:39.798(-7)?
I20160804-18:28:39.798(-7)?
I20160804-18:28:39.798(-7)? --------------------------------
I20160804-18:28:39.798(-7)? ----- RUNNING CLIENT TESTS -----
I20160804-18:28:39.799(-7)? --------------------------------
I20160804-18:28:39.799(-7)?
=> Started your app.

=> App running at: http://localhost:3000/
I20160804-18:28:40.947(-7)?
I20160804-18:28:40.948(-7)?
I20160804-18:28:40.967(-7)?   data available when routed
I20160804-18:28:40.967(-7)?     when logged out
I20160804-18:28:41.262(-7)? MochaRunner.runServerTests: Starting server side tests with run id D9WeFBAGwwSSxobms
W20160804-18:28:41.265(-7)? (STDERR) MochaRunner.runServerTests: failures: 0
I20160804-18:28:41.296(-7)? ClientServerReporter.constructor: Missing reporter to run tests. Use MochaRunner.setReporter(reporter) to set one.

I20160804-18:28:41.595(-7)?       ✓ has all public lists at homepage
I20160804-18:28:41.598(-7)? stdout:

I20160804-18:28:42.136(-7)?       ✓ renders the correct list when routed to (202ms)
I20160804-18:28:42.137(-7)? stdout:
I20160804-18:28:42.138(-7)?
I20160804-18:28:42.138(-7)?
I20160804-18:28:42.138(-7)?   2 passing (1s)
I20160804-18:28:42.139(-7)?
I20160804-18:28:45.808(-7)? All client and server tests finished!
I20160804-18:28:45.808(-7)?
I20160804-18:28:45.809(-7)? --------------------------------
I20160804-18:28:45.809(-7)? SERVER FAILURES: 0
I20160804-18:28:45.810(-7)? CLIENT FAILURES: 0
I20160804-18:28:45.810(-7)? --------------------------------
```

**Comment by DominikGuzei** [comment]
ok nice, last time i checked they failed – maybe someone repaired them already 😉

**Comment by noahsw** [comment]
Cool, I'll try to add them back to CI in #172

**Comment by noahsw** [comment]
Btw - it'd be great if your testing scripts were broken out into an npm package. I'm sure they'd be very useful to many other Meteor apps!

**Pull request merged**
