### PR TITLE
#20 Adding Google OAuth

### PR DESCRIPTION
**Pull request by NickBusey**
This enables Google OAuth. The button isn't really styled so it's just kinda red, but it all works fine.

### CODE REVIEW

**Comment by hwillson** [comment]
Hi @NickBusey - sorry for the delay in responding to this. Are you still interested in working on this? If so, could you rebase your PR to get the latest changes from `master`? I'll then review - thanks!

**Comment by NickBusey** [comment]
@hwillson sure

**Comment by abernix** [comment]
@NickBusey Did you ever get a chance to consider rebasing this?

**Comment by NickBusey** [comment]
@abernix I tried, but it looks like there is a bug with the new service-configuration package version. It should be just two things, running `meteor add accounts-ui accounts-google service-configuration` and changing app-body.js:emailLocalPart() to:

```
  displayName() {
    let displayName = '';
    if (Meteor.user().emails) {
      const email = Meteor.user().emails[0].address;
      displayName = email.substring(0, email.indexOf('@'));
    } else {
      displayName = Meteor.user().profile.name;
    }
    return displayName;
  },
```

I don't have any more time to dedicate to this PR though. Best of luck.

**Pull request closed without merging**
