### PR TITLE
Removed local stub-collections package.

### PR DESCRIPTION
**Pull request by hwillson**
Hi guys - also relating to #119. I've removed the local `stub-collections` copy from the `react` branch. Thanks!

### CODE REVIEW

**Comment by tmeasday** [comment]
@hwillson this seems to have some merge issues?

**Comment by hwillson** [comment]
Hi @tmeasday - sorry, I had to run out and just noticed as well. I'll get this fixed. Thanks!

**Comment by hwillson** [comment]
It should be all set now @tmeasday - not enough coffee today!

**Comment by tmeasday** [comment]
Thanks!

**Pull request merged**
